### ISSUE TITLE
Crashes in 50.2 (55047)

### ISSUE THREAD

**Issue by chanjohnathan** [contentsync/SketchContentSync#71] opened 2018-06-29 15:55 UTC
I installed this plugin today and Sketch immediately crashes. I tried looking at the plugin console, but nothing comes up.

**Comment by dbrody** [comment] 2018-06-29 16:39
@chanjohnathan - Uh oh! Was this for a new install or an update?

**Comment by dbrody** [comment] 2018-06-29 17:11
@chanjohnathan - So our login relies on something called `WKWebView` which is only supported on MacOS 10.12 and up. We'll look into a software fix to support prior to 10.12 but it wont be a quick fix. Other than that, I'll see if there is some other way we can get you started. Sorry for the inconvenience.

**Comment by lmjabreu-poq** [comment] 2018-07-03 17:29
I'm experiencing crashes on 50.2 after updating to the latest version. Seems related to a bug surrounding the sidebar extension as I cannot reorder layers when ContentSync is enabled, once I disable ContentSync and restart Sketch layers can be reordered once more. There's also some broken behaviour around adding a new version, seems to have got out of sync with the spreadsheet even when I refresh from google sheets. Also, pushing return a 'object cannot be nil'.

**Comment by dbrody** [comment] 2018-07-03 17:35
@lmjabreu-poq - I just uploaded [release 4.2.1](https://github.com/contentsync/SketchContentSync/releases/tag/4.2.1) to address a couple issues - including the error you mentioned.

I'll file the layer reordering issue and see what we can do about that.

**Comment by dbrody** [comment] 2018-07-05 19:08
@chanjohnathan - I'm going to close this issue due to lack of details / followup. As mentioned before, it may be due to MacOS 10.11 as our login panel relies on MacOS 10.12 features and up.

@lmjabreu-poq - We're unable to reproduce the layer reordering issue you mentioned. If you run into the issue again, can you file a new issue with more details.

Please open new issues with any follow up items and provide as many details as you can.

Thanks guys for giving feedback!
David

**Closed by dbrody** 2018-07-05 19:08 UTC

**Comment by dbrody** [comment] 2018-07-05 19:37
@lmjabreu-poq - [Release 4.2.2](https://github.com/contentsync/SketchContentSync/releases/tag/4.2.2) addresses the version dropdown issue you mentioned when creating a new version.

**Comment by lmjabreu** [comment] 2018-07-06 08:53
@dbrody can't replicate the ordering issue anymore, I'm experiencing some sluggishness and syncing issues though, have recorded a video and shared via email that includes os version, problematic file, and demo of the issues.
